package com.puutaro.commandclick.common.variable.res

import com.puutaro.commandclick.R
import com.puutaro.commandclick.util.file.ButtonAssetsImage

enum class CmdClickIcons(
    val str: String,
    val id: Int,
    val assetsPath: String
) {
    ABOUT("about", R.drawable.icons8_about, ButtonAssetsImage.aboutPingPath),
    BACK("back", R.drawable.back, ButtonAssetsImage.backPingPath),
    CANCEL("cancel", R.drawable.icons8_cancel, ButtonAssetsImage.cancelPingPath),
    CC("cc", R.drawable.cc, ButtonAssetsImage.cPingPath),
    COPY("copy", androidx.appcompat.R.drawable.abc_ic_menu_copy_mtrl_am_alpha, ButtonAssetsImage.copyPingPath),
    DOWN("down", R.drawable.ic_down_allow, ButtonAssetsImage.downPingPath),
    DOWNLOAD("download", android.R.drawable.stat_sys_download, ButtonAssetsImage.downloadDonePingPath),
    DOWNLOAD_COMP("download_done", android.R.drawable.stat_sys_download_done, ButtonAssetsImage.downloadDonePingPath),
    DEBUG("debug", R.drawable.icon_debug, ButtonAssetsImage.debugPingPath),
    EDIT("edit", R.drawable.icons8_edit, ButtonAssetsImage.editPingPath),
    EDIT_FRAME("edit_frame", R.drawable.icons8_edit_frame, ButtonAssetsImage.editPingPath),
    EXTRA("extra", R.drawable.extra, ButtonAssetsImage.extraPingPath),
    FILE("file", R.drawable.icons8_file, ButtonAssetsImage.filePingPath),
    FOLDA("folda", R.drawable.icons8_folda, ButtonAssetsImage.foldaPingPath),
    FORWARD("forward", R.drawable.icon_forward, ButtonAssetsImage.forwardPingPath),
    GOOGLE("google", R.drawable.google, ButtonAssetsImage.googlePingPath),
    GOOGLE2("google2", R.drawable.google, ButtonAssetsImage.google2PingPath),
    HISTORY("history", R.drawable.icons8_history, ButtonAssetsImage.fannelManagerPath),
    GALLERY("gallery", R.drawable.icons8_image_gallery, ButtonAssetsImage.galleryPingPath),
    JS("js", R.drawable.js, ButtonAssetsImage.jsPingPath),
    INFO("info", R.drawable.icons8_info, ButtonAssetsImage.infoPingPath),
    INTERNET("internet", R.drawable.internet, ButtonAssetsImage.internetPingPath),
    LAUNCH("launch", R.drawable.icons8_launch, ButtonAssetsImage.launchPingPath),
    LIST("list", R.drawable.icons8_list, ButtonAssetsImage.listPingPath),
    LONG_PRESS("long_press", R.drawable.long_press, ButtonAssetsImage.longPressPingPath),
    MAIL("mail", R.drawable.icons8_mail, ButtonAssetsImage.mailPingPath),
    MINUS("minus", R.drawable.minus, ButtonAssetsImage.minusPingPath),
    MENU("menu", R.drawable.icons8_menu, ButtonAssetsImage.menuPingPath),
    MUSIC("music", R.drawable.icon_music, ButtonAssetsImage.musicPingPath),
    OK("ok", R.drawable.icons8_check_ok, ButtonAssetsImage.okPingPath),
    OPEN_CLOSE("open_close", R.drawable.open_and_close, ButtonAssetsImage.openClosePingPath),
    OVERFLOW("overflow", androidx.appcompat.R.drawable.abc_ic_menu_overflow_material, ButtonAssetsImage.overflowPingPath),
    PIN("pin", R.drawable.pin, ButtonAssetsImage.pinPingPath),
    PIN_LOCATION("pin_location", R.drawable.pin_location, ButtonAssetsImage.pinLocationPingPath),
    PLAY("play", R.drawable.icons_play, ButtonAssetsImage.playPingPath),
    PREF("pref", R.drawable.pref, ButtonAssetsImage.prefPingPath),
    PUZZLE("puzzle", R.drawable.icons8_puzzle, ButtonAssetsImage.puzzlePingPath),
    PLUS("plus", R.drawable.icons8_plus, ButtonAssetsImage.plusPingPath),
    QR("qr", R.drawable.icons_qr_code, ButtonAssetsImage.qrPingPath),
    ROUND_RECT("round_rect", R.drawable.round_rect, ButtonAssetsImage.roundRectPath),
    RECT("rect", R.drawable.rect, ButtonAssetsImage.rectPingPath),
    REFLESH("reflesh", R.drawable.icons8_refresh, ButtonAssetsImage.refleshPingPath),
    RIGHT_TRIANGLE("triangle_right", R.drawable.right_triangle, ButtonAssetsImage.triangleRightPingPath),
    RING("ring", R.drawable.icons8_wheel, ButtonAssetsImage.wheelPingPath),
    SET_UP("setup", R.drawable.icons8_setup, ButtonAssetsImage.setupPingPath),
    SEARCH("search", R.drawable.icons8_search, ButtonAssetsImage.searchPingPath),
    SETTING("setting", R.drawable.icons8_setting, ButtonAssetsImage.settingPingPath),
    SHARE("share", R.drawable.icons8_share, ButtonAssetsImage.sharePingPath),
    SHORTCUT("shortcut", R.drawable.icons8_shortcut, ButtonAssetsImage.shortcutPingPath),
    STAR("star", R.drawable.icon_star, ButtonAssetsImage.starPingPath),
    SUPPORT("support", R.drawable.icons8_support, ButtonAssetsImage.supportPingPath),
    SPIDER("spider", R.drawable.spider, ButtonAssetsImage.spiderPingPath),
    TERMINAL("terminal", R.drawable.ic_terminal, ButtonAssetsImage.terminalPingPath),
    TOP("top", R.drawable.ic_top_allow, ButtonAssetsImage.topPingPath),
    BLACK_HISTORY("black_history", R.drawable.black_history_icons, ButtonAssetsImage.blackHistoryPath),
    UPDATE("update", R.drawable.icons8_update, ButtonAssetsImage.updatePingPath),
    WHEEL("wheel", com.skydoves.colorpickerview.R.drawable.wheel, ButtonAssetsImage.wheelPingPath),
}