package com.puutaro.commandclick.common.variable.icon

import com.puutaro.commandclick.R

enum class CmdClickIcons(
    val str: String,
    val id: Int,
) {
    ABOUT("about", R.drawable.icons8_about),
    BACK("back", com.afollestad.materialdialogs.R.drawable.md_nav_back),
    CANCEL("cancel", R.drawable.icons8_cancel),
    COPY("copy", androidx.appcompat.R.drawable.abc_ic_menu_copy_mtrl_am_alpha),
    DOWN("down", R.drawable.ic_down_allow),
    DOWNLOAD("download", android.R.drawable.stat_sys_download),
    DOWNLOAD_COMP("download_done", android.R.drawable.stat_sys_download_done),
    EDIT("edit", R.drawable.icons8_edit),
    EDIT_FRAME("edit_frame", R.drawable.icons8_edit_frame),
    FILE("file", R.drawable.icons8_file),
    FOLDA("folda", R.drawable.icons8_folda),
    HISTORY("history", R.drawable.icons8_history),
    INFO("info", R.drawable.icons8_info),
    INTERNET("internet", R.drawable.internet),
    LAUNCH("launch", R.drawable.icons8_launch),
    LIST("list", R.drawable.icons8_list),
    MENU("menu", R.drawable.icons8_menu),
    OK("ok", R.drawable.icons8_check_ok),
    OVERFLOW("oeverflow", androidx.appcompat.R.drawable.abc_ic_menu_overflow_material),
    PLAY("play", R.drawable.icons_play),
    PUZZLE("puzzle", R.drawable.icons8_puzzle),
    PLUS("plus", R.drawable.icons8_plus),
    QR("qr", R.drawable.icons_qr_code),
    REFLESH("reflesh", R.drawable.icons8_refresh),
    RING("ring", R.drawable.icons8_wheel),
    SET_UP("setup", R.drawable.icons8_setup),
    SEARCH("search", R.drawable.icons8_search),
    SETTING("setting", R.drawable.icons8_setting),
    SHARE("share", R.drawable.icons8_share),
    SHORTCUT("shortcut", R.drawable.icons8_shortcut),
    SUPPORT("support", R.drawable.icons8_support),
    TERMINAL("terminal", R.drawable.ic_terminal),
    UPDATE("update", R.drawable.icons8_update),
    WHEEL("wheel", com.skydoves.colorpickerview.R.drawable.wheel),
}