package com.puutaro.commandclick.common.variable.res

import com.puutaro.commandclick.R

enum class FannelIcons(
    val str: String,
    val id: Int,
) {
    AIRPHANE(
        "airphane",
        R.drawable.fannel_airphane
    ),
    AIRPHANE_DEFO(
        "airphane_defo",
        R.drawable.fannel_airphane_defo
    ),
    AT_MARK(
        "airphane",
        R.drawable.fannel_at_mark
    ),
//    AWARD(
//        "award",
//        R.drawable.fannel_award
//    ),
    BALLOON(
        "balloon",
        R.drawable.fannel_balloon
    ),
    BIRD(
        "bird",
        R.drawable.fannel_bird
    ),
    BULLET_TRAIN(
        "bullet_train",
        R.drawable.fannel_bullet_train
    ),
    CAT_FACE1(
        "cat_face",
        R.drawable.fannel_cat_face
    ),
    CHECKER(
        "checker",
        R.drawable.fannel_checker
    ),
    CHOUTIN(
        "choutin",
        R.drawable.fannel_choutin
    ),
    CORSAIR(
        "corsair",
        R.drawable.fannel_cosair
    ),
    CROCODILE(
        "crocodile",
        R.drawable.fannel_crocodile
    ),
    CROWN(
        "crown",
        R.drawable.fannel_crown
    ),
    BRAIN(
        "brain",
        R.drawable.fannel_brain
    ),
    DOG_FACE(
        "dog_face",
        R.drawable.fannel_dog_face
    ),
    DOG_FOOTPRINT(
        "dog_footprint",
        R.drawable.fannel_dog_footprint
    ),
    DOLL_MARK(
        "doll_mark",
        R.drawable.fannel_doll_mark
    ),
    DOLPHIN(
        "dolphin",
        R.drawable.fannel_dolphin
    ),
    DRAGON(
        "dragon",
        R.drawable.fannel_dragon
    ),
    EAGLE(
        "eagle",
        R.drawable.fannel_eagle
    ),
    ELEPHANT(
        "elephant",
        R.drawable.fannel_elephant
    ),
    ELEPHANT_PAHOO(
        "elephant_pahoo",
        R.drawable.fannel_elephant_pahoo
    ),
    FIRE(
        "fire",
        R.drawable.fannel_fire
    ),
    FUJI(
        "fuji",
        R.drawable.fannel_fuji
    ),
    F1(
        "f1",
        R.drawable.fannel_f1
    ),
    F1_DASH(
        "f1_dash",
        R.drawable.fannel_f1_dash
    ),
    GE(
        "ge",
        R.drawable.fannel_ge
    ),
    GOJIRA(
        "gojira",
        R.drawable.fannel_gojira
    ),
    GUNDAM(
        "gundam",
        R.drawable.fannel_gundam
    ),
    HAKUSHOKU_SUISEI(
        "hakushoku_suisei",
        R.drawable.fannel_hakushoku_suisei
    ),
    HIME(
        "hime",
        R.drawable.fannel_hime1
    ),
    HIME2(
        "hime2",
        R.drawable.fannel_hime2
    ),
    JANOMITI(
        "janomiti",
        R.drawable.fannel_janomiti
    ),
    JANOMITI2(
        "janomiti2",
        R.drawable.fannel_janomiti2
    ),
    JINJA(
        "jinja",
        R.drawable.fannel_jinja1
    ),
    JINJA2(
        "jinja2",
        R.drawable.fannel_jinja2
    ),
    JINJA3(
        "jinja3",
        R.drawable.fannel_jinja3
    ),
    JK(
        "jk",
        R.drawable.fannel_jk
    ),
    JOU(
        "jou",
        R.drawable.fannel_jou
    ),
    KABUTO(
        "kabuto",
        R.drawable.fannel_kabuto
    ),
    KABUTO2(
        "kabuto2",
        R.drawable.fannel_kabuto2
    ),
    KABUTO3(
        "kabuto3",
        R.drawable.fannel_kabuto3
    ),
    KABUTO4(
        "kabuto4",
        R.drawable.fannel_kabuto4
    ),
    KITUNE(
        "kitune",
        R.drawable.fannel_kitune
    ),
    KNIGHT(
        "knight",
        R.drawable.fannel_knight
    ),
    KUJIRA(
        "kujira",
        R.drawable.fannel_kujira
    ),
    LABRADOR(
        "labrador",
        R.drawable.fannel_labrador
    ),
    LION_FACE(
        "lion_face",
        R.drawable.fannel_lion_face
    ),
    MAGATAMA(
        "magatama",
        R.drawable.fannel_magatama
    ),
    MOON(
        "moon",
        R.drawable.fannel_moon
    ),
    OCTOPASS(
        "octopass",
        R.drawable.fannel_octopass
    ),
    OCTOPASS2(
        "octopass2",
        R.drawable.fannel_octopass2
    ),
    OMUSUBI(
        "omusubi",
        R.drawable.fannel_omusubi
    ),
    OTHER_MOON(
        "other_moon",
        R.drawable.fannel_other_moon
    ),
    ROBOT(
        "robot",
        R.drawable.fannel_robot
    ),
    PHANTOM(
        "phantom",
        R.drawable.fannel_phantom
    ),
    PHENIX(
        "phenix",
        R.drawable.fannel_phenix1
    ),
    PHENIX2(
        "phenix2",
        R.drawable.fannel_phenix2
    ),
    ROCKET(
        "rocket",
        R.drawable.fannel_rocket
    ),
    ROYAL_NAVY(
        "royal_navy",
        R.drawable.fannel_royal_navy
    ),
    SAMURAI(
        "samurai",
        R.drawable.fannel_samurai
    ),
    SAMURAI2(
        "samurai2",
        R.drawable.fannel_samurai2
    ),
    SENSE(
        "sense",
        R.drawable.fannel_sense
    ),
    SHACHI(
        "shachi",
        R.drawable.fannel_shachi
    ),
    SHATIHOKO(
        "shatihoko",
        R.drawable.fannel_shatihoko
    ),
    SHARK(
        "shark",
        R.drawable.fannel_shark
    ),
    SHEPARD(
        "shepard",
        R.drawable.fannel_shepard
    ),
    SIRO(
        "siro",
        R.drawable.fannel_siro
    ),
    SKULL(
        "skull",
        R.drawable.fannel_skull
    ),
    SKULL_HORIZON(
        "skull",
        R.drawable.fannel_skull_horizon
    ),
    SNAKE(
        "snake",
        R.drawable.fannel_snake
    ),
    SNAKE_BODY(
        "snake_body",
        R.drawable.fannel_snake_body
    ),
    SOBA(
        "soba",
        R.drawable.fannel_soba
    ),
    STAR(
        "star",
        R.drawable.fannel_star
    ),
    SUSHI(
        "sushi",
        R.drawable.fannel_sushi
    ),
    TEN(
        "ten",
        R.drawable.fannel_ten
    ),
    TIGER(
        "tiger",
        R.drawable.fannel_tiger
    ),
    TIGER_YOKO(
        "tiger_yoko",
        R.drawable.fannel_tiger_yoko
    ),
    TRAIN(
        "train",
        R.drawable.fannel_train
    ),
    TREX(
        "trex",
        R.drawable.fannel_trex
    ),
    TROPHY(
        "trophy",
        R.drawable.fannel_trophy
    ),
    WIND(
        "wind",
        R.drawable.fannel_wind
    ),
}