package com.puutaro.commandclick.common.variable.edit

enum class EditTextSupportViewName(
    val str: String
) {
    VARIABLE_LABEL("LBL"),
    CHECK_BOX("CB"),
    EDITABLE_CHECK_BOX("ECB"),
    LIST_CONTENTS_SELECT_BOX("LSB"),
    EDITABLE_LIST_CONTENTS_SELECT_BOX("ELSB"),
    LIST_CONTENTS_MULTI_SELECT_BOX("LMSB"),
    EDITABLE_FILE_SELECT_BOX("FSB"),
    GRID_BOX("GB"),
    MULTI_GRID_BOX("MGB"),
    ONlY_IMAGE_GRID_BOX("IGB"),
    FILE_SELECT_GRID_BOX("FGB"),
    FILE_SELECT_ONLY_IMAGE_GRID_BOX("FIGB"),
    MULTI_FILE_SELECT_GRID_BOX("MFGB"),
    DRAG_SORT_SELECT_BOX("DSL"),
    MULTI_SELECT_BOX("MSB"),
    FILE_PICKER("FL"),
    DIRECTORY_PICKER("DIR"),
    NUM_INDE_CREMENTER("NUM"),
    BUTTON("BTN"),
    EDIT_TEXT_EMPHASIS("TXT"),
    READ_ONLY_EDIT_TEXT("RO"),
    PASSWORD("H"),
    HIDDEN_LABEL("HL"),
    DATE("DT"),
    TIME("TM"),
    COLOR("CLR"),
    LIST_INDEX("LI"),
}
