package com.puutaro.commandclick.common.variable.edit

enum class EditTextSupportViewName(
    val str: String
) {
    EDITABLE_BUTTON("EB"),
    CHECK_BOX("CB"),
    CHECK_BOX_BUTTON("CBB"),
    EDITABLE_CHECK_BOX("ECB"),
    EDITABLE_CHECK_BOX_BUTTON("ECBB"),
    EDITABLE_FILE_CHECK_BOX("EFCB"),
    EDITABLE_FILE_CHECK_BOX_BUTTON("EFCBB"),
    MDIRECTORY_PICKER("MDIR"),
    DIRECTORY_PICKER("DIR"),
    DIRECTORY_PICKER_BUTTON("DIRB"),
    MFILE_PICKER("MFL"),
    FILE_PICKER("FL"),
    FILE_PICKER_BUTTON("FLB"),
    NUM_INDE_CREMENTER("NUM"),
    NUM_INDE_CREMENTER_BUTTON("NUMB"),
    READ_ONLY_EDIT_TEXT("RO"),
    PASSWORD("H"),
    BUTTON("BTN"),
    FBUTTON("FBTN"),
    DATE("DT"),
    TIME("TM"),
    COLOR("CLR"),
    COLOR_BUTTON("CLRB"),

}