package com.puutaro.commandclick.proccess.tool_bar_button.common_settings

enum class JsPathMacroForToolbarButton{
    KILL,
    USAGE,
    NO_SCROLL_SAVE_URL,
    QR_SCAN,
    SHORTCUT,
    TERMUX_SETUP,
    CONFIG,
    ADD_URL_HISTORY,
    REFRESH_MONITOR,
    SELECT_MONITOR,
    RESTART_UBUNTU,
    INSTALL_FANNEL,
    EDIT_STARTUP,
    JS_IMPORT,
    ADD,
    ADD_APP_DIR,
    APP_DIR_MANAGER,
    SIZING,
    MENU,
    SYNC,
    GET_FILE,
    GET_QR_CON,
    FANNEL_REPO_SYNC,
    EDIT,
    WEB_SEARCH,
    PAGE_SEARCH,
    NORMAL,
    OK,
}