#!/bin/bash

set -e

read_args(){
	local STR=""
	local index=0
	while (( $# > 0 ))
	do
	case "${1}" in
	    --help|-h)
	        HELP="${1}"
	        ;;
	    -*) ;;
	    *)
			ARG[index]="${1}"
			index="$(( ${index} + 1 ))"
			;;
	esac
	shift
	done <<- END
	$STR
	END
}

get_help(){
	case "${HELP}" in
		"") ;;
		*) 
			awk \
			'BEGIN{
				print "### Replace variables getter"
				print ""
				print ""
				print "## Usage"
				print ""
				print "# Get replace variables contents"
				print "get_rvar \x22${contents}\x22 \x22${replace variables name}\x22"
				print ""
				print ""
				print " js -> shell"
				print ""
				print "# Get variable by variable name"
				print "get_rvar \x22${contents}\x22 \x22${replace variables name}\x22"
				print ""
				print ""
				print " shell ->"
				print ""
				print "get_rvar \x22${contents}\x22 \x22${replace variables name}\x22 \x22${fannel dir path include path}\x22"
				print ""
				print "* pre reaserved word for only shell"
				print ""
				print "\t ${00} -> app_root_path"
				print "\t ${01} -> current_app_dir_path"
				print "\t ${001} -> fannel_dir_name"
				print "\t ${02} -> fannel_shell_name"
				print "\t ${0} -> fannel_shell_path"
				print ""
			}'
			exit 0
		;;
	esac
}

get_replace_variables(){
	local current_file_path="${1}"

	case "${current_file_path}" in
		 "") echo ""; exit 0;;
	esac
	local fannel_dir_path=$(\
		awk \
		-v current_file_path="${current_file_path}"\
		-v APP_DIR_PATH="${APP_ROOT_PATH}/AppDir" \
		'BEGIN {
			app_dir_relative_path = current_file_path
			gsub(APP_DIR_PATH"/", "", app_dir_relative_path)
			size = split( app_dir_relative_path , app_dir_relative_path_array, "/" )
			fannnel_dir_relative_path = app_dir_relative_path_array[1]"/"app_dir_relative_path_array[2] 
			print APP_DIR_PATH"/"fannnel_dir_relative_path
		}' \
	)
	local replace_variables_table_path="${fannel_dir_path}/${REPLACE_VARIABLES_TSV_RELATIVE_PATH}"
	test ! -f "${replace_variables_table_path}" && exit 0 || e=$?
	cat "${replace_variables_table_path}"
}

grep_key(){
	local con="${1}"
	local key="${2}"
	local current_file_path="${3:-}"
	awk \
		-v con="${con}" \
		-v key="${key}" \
		-v current_file_path="${current_file_path}"\
		-v APP_ROOT_PATH="${APP_ROOT_PATH}" \
		-v APP_DIR_PATH="${APP_ROOT_PATH}/AppDir" \
		'BEGIN {
			# make pre reserved word for shell
			if(current_file_path){
				app_dir_relative_path = current_file_path
				gsub(APP_DIR_PATH"/", "", app_dir_relative_path)
				size = split( app_dir_relative_path , app_dir_relative_path_array, "/" )
				current_app_dir_name = app_dir_relative_path_array[1]
				current_app_dir_path = APP_DIR_PATH"/"app_dir_relative_path_array[1]
				fannel_dir_name = app_dir_relative_path_array[2]
				fannnel_dir_relative_path = current_app_dir_name"/"fannel_dir_name
				fannel_dir_path = APP_DIR_PATH"/"fannnel_dir_relative_path
				fannel_shell_name = fannel_dir_name
				sub(/Dir$/, ".sh", fannel_shell_name)
				fannel_shell_path = current_app_dir_path"/"fannel_shell_name
			}
			# grep
			grep_key = key"\t"
			index_grep_key = index(con, grep_key)
			if(index_grep_key < 0) exit
			slice_con = substr(con, index_grep_key, length(con))
			sub(/\n.*/, "", slice_con)
			sub(/.*\t/, "", slice_con)
			gsub("\${00}", APP_ROOT_PATH, slice_con)
			gsub("\${01}", current_app_dir_path, slice_con)
			gsub("\${001}", fannel_dir_name, slice_con)
			gsub("\${02}", fannel_shell_name, slice_con)
			gsub("\${0}", fannel_shell_path, slice_con)
			print slice_con
		}'
}

HELP=""
ARG=()
read_args "$@"
get_help

case "${ARG[@]}" in
	"") exit 1;;
esac

ARG0="${ARG[0]}"
KEY_NAME="${ARG[1]}"
CURRENT_FILE_PATH="${ARG[2]:-}"

if [ -e "${ARG0}"  ];then
	get_replace_variables "${ARG0}"
else 
	grep_key "${ARG0}" "${KEY_NAME}" "${CURRENT_FILE_PATH}"
fi
