package com.puutaro.commandclick.util.file

object ButtonAssetsImage {
    const val resButtonPngDirPath = "${AssetsFileManager.resPngDirPath}/button"
    const val fannelManagerPath = "${resButtonPngDirPath}/fannel_manager.png"
    const val searchPingPath = "${resButtonPngDirPath}/search.png"
    const val settingPingPath = "${resButtonPngDirPath}/setting.png"
    const val urlHistoryPingPath = "${resButtonPngDirPath}/url_history.png"
    const val downPingPath = "${resButtonPngDirPath}/down.png"
    const val topPingPath = "${resButtonPngDirPath}/top.png"
    const val aboutPingPath = "${resButtonPngDirPath}/about.png"
    const val cancelPingPath = "${resButtonPngDirPath}/cancel.png"
    const val copyPingPath = "${resButtonPngDirPath}/copy.png"
    const val backPingPath = "${resButtonPngDirPath}/back.png"
    const val blackHistoryPath = "${resButtonPngDirPath}/black-history-icons.png"
    const val downloadDonePingPath = "${resButtonPngDirPath}/download_done.png"
    const val debugPingPath = "${resButtonPngDirPath}/debug.png"
    const val editPingPath = "${resButtonPngDirPath}/edit.png"
    const val filePingPath = "${resButtonPngDirPath}/file.png"
    const val foldaPingPath = "${resButtonPngDirPath}/folda.png"
    const val forwardPingPath = "${resButtonPngDirPath}/forward.png"
    const val galleryPingPath = "${resButtonPngDirPath}/gallery.png"
    const val infoPingPath = "${resButtonPngDirPath}/info.png"
    const val jsPingPath = "${resButtonPngDirPath}/js.png"
    const val internetPingPath = "${resButtonPngDirPath}/internet.png"
    const val launchPingPath = "${resButtonPngDirPath}/launch.png"
    const val listPingPath = "${resButtonPngDirPath}/list.png"
    const val longPressPingPath = "${resButtonPngDirPath}/long_press.png"
    const val mailPingPath = "${resButtonPngDirPath}/mail.png"
    const val minusPingPath = "${resButtonPngDirPath}/minus.png"
    const val menuPingPath = "${resButtonPngDirPath}/menu.png"
    const val musicPingPath = "${resButtonPngDirPath}/music.png"
    const val okPingPath = "${resButtonPngDirPath}/ok.png"
    const val openClosePingPath = "${resButtonPngDirPath}/open_close.png"
    const val overflowPingPath = "${resButtonPngDirPath}/overflow.png"
    const val pinPingPath = "${resButtonPngDirPath}/pin.png"
    const val pinLocationPingPath = "${resButtonPngDirPath}/pin_location.png"
    const val playPingPath = "${resButtonPngDirPath}/play.png"
    const val puzzlePingPath = "${resButtonPngDirPath}/puzzle.png"
    const val qrPingPath = "${resButtonPngDirPath}/qr.png"
    const val refleshPingPath = "${resButtonPngDirPath}/reflesh.png"
    const val setupPingPath = "${resButtonPngDirPath}/setup.png"
    const val sharePingPath = "${resButtonPngDirPath}/share.png"
    const val shortcutPingPath = "${resButtonPngDirPath}/shortcut.png"
    const val starPingPath = "${resButtonPngDirPath}/star.png"
    const val supportPingPath = "${resButtonPngDirPath}/support.png"
    const val terminalPingPath = "${resButtonPngDirPath}/terminal.png"
    const val updatePingPath = "${resButtonPngDirPath}/update.png"
    const val wheelPingPath = "${resButtonPngDirPath}/wheel.png"
    const val plusPingPath = "${resButtonPngDirPath}/plus.png"

}