package com.puutaro.commandclick.common.variable.intent

enum class BroadCastIntentScheme(
    val action: String,
    val scheme: String
) {
    MONITOR_TEXT_PATH(
        "com.puutaro.commandclick.url.monitor_text_path",
        "monitor_text_path"
    ),
    MONITOR_MANAGER(
        "com.puutaro.commandclick.url.monitor_manager",
        "monitor_manager"
    ),
    ULR_LAUNCH(
        "com.puutaro.commandclick.url.launch",
        "url",
    ),
    HTML_LAUNCH(
    "com.puutaro.commandclick.html.launch",
    "edit_path",
    ),
    FZHTML_LAUNCH(
        "com.puutaro.commandclick.fzhtml.launch",
        "edit_path",
    ),
    STOP_GIT_CLONE(
    "com.puutaro.commandclick.git_clone_stop.launch",
    "stop",
    ),
    STOP_TEXT_TO_MP3(
        "com.puutaro.commandclick.text_to_mp3.launch",
        "stop",
    ),
    STOP_TEXT_TO_SPEECH(
        "com.puutaro.commandclick.text_to_speech.stop",
        "stop",
    ),
    PREVIOUS_TEXT_TO_SPEECH(
        "com.puutaro.commandclick.text_to_speech.previous",
        "previous",
    ),
    FROM_TEXT_TO_SPEECH(
        "com.puutaro.commandclick.text_to_speech.from",
        "from",
    ),
    NEXT_TEXT_TO_SPEECH(
        "com.puutaro.commandclick.text_to_speech.next",
        "next",
    ),
    TO_TEXT_TO_SPEECH(
        "com.puutaro.commandclick.text_to_speech.to",
        "to",
    ),
    STOP_PULSE_RECIEVER(
        "com.puutaro.commandclick.pulse_server.stop",
        "stop",
    ),
    RESTART_PULSE_RECIEVER(
        "com.puutaro.commandclick.pulse_server.restart",
        "restart",
    ),
    START_UBUNTU_SERVICE(
        "com.puutaro.commandclick.ubuntu_service.start",
        "start",
    ),
    STOP_UBUNTU_SERVICE(
        "com.puutaro.commandclick.ubuntu_service.stop",
        "stop",
    ),
    UPDATE_PROCESS_NUM_NOTIFICATION(
        "com.puutaro.commandclick.ubuntu_service.update_process_num",
        "update_process_num",
    ),
    IS_ACTIVE_UBUNTU_SERVICE(
        "com.puutaro.commandclick.ubuntu_service.is_active",
        "is_active",
    ),
    CMD_KILL_BY_ADMIN(
        "com.puutaro.commandclick.ubuntu_service.background_cmd_kill",
        "background_cmd_kill",
    ),
    BACKGROUND_CMD_START(
        "com.puutaro.commandclick.ubuntu_service.background_cmd_start",
        "background_cmd_start",
    ),
    ADMIN_CMD_START(
        "com.puutaro.commandclick.ubuntu_service.admin_cmd_start",
        "admin_cmd_start",
    ),
    RESTART_UBUNTU_SERVICE_FROM_ACTIVITY(
        "com.puutaro.commandclick.ubuntu_service.restart",
        "restart",
    ),
    OPEN_FANNEL(
        "com.puutaro.commandclick.ubuntu_service.open_fannel",
        "open_fannel",
    ),
    WIFI_WAIT_NITIFICATION(
        "com.puutaro.commandclick.ubuntu_service.wifi_wait",
        "wifi_wait",
    ),
    ON_UBUNTU_SETUP_NOTIFICATION(
        "com.puutaro.commandclick.ubuntu_service.on_ubuntu_setup",
        "on_ubuntu_setup",
    ),
    ON_UBUNTU_SETUP_QUIZ_NOTIFICATION(
        "com.puutaro.commandclick.ubuntu_service.on_ubuntu_setup_quiz",
        "on_ubuntu_setup_quiz",
    ),
    ON_RUNNING_NOTIFICATION(
        "com.puutaro.commandclick.ubuntu_service.on_running",
        "on_running",
    ),
    ON_SLEEPING_NOTIFICATION(
        "com.puutaro.commandclick.ubuntu_service.sleeping",
        "sleeping",
    ),
    FOREGROUND_CMD_START(
        "com.puutaro.commandclick.ubuntu_service.shell2http",
        "shell2http",
    ),
}